name: Daily Wikipedia Podcast Generation

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 1 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-podcast:
    runs-on: ubuntu-latest
    environment: Daily Generator
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: PocketCoder/ephemera
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsndfile1 espeak

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate Podcast
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        python main.py
    
    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        
        # Check if there are any new .mp3 files
        if [ -n "$(find output -name '*.mp3')" ]; then
          git add output/0/*.mp3
          git commit -m "Add daily podcast $(date +'%Y-%m-%d')"
          git push
        else
          echo "No new podcast files to commit"
        fi