name: Daily Wikipedia Podcast Generation

on:
  schedule:
    - cron: '0 1 * * *'  # 1 AM UTC daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-podcast:
    runs-on: macos-latest
    environment: Daily Generator
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: PocketCoder/ephemera
        fetch-depth: 0

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Cache Homebrew
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/Homebrew
          /usr/local/Cellar
        key: brew-${{ runner.os }}-${{ hashFiles('Brewfile') }}
        restore-keys: |
          brew-${{ runner.os }}-

    - name: Install Homebrew dependencies
      run: |
        export HOMEBREW_BREWFILE=~/.brewfile
        brew bundle install --no-lock
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone Kokoro-82M
      run: |
        git lfs install
        git clone https://huggingface.co/hexgrad/kLegacy Kokoro-82M

    - name: Setup virtual display
      uses: GabrielBB/xvfb-action@v1
      with:
        run: chromedriver --url-base=/wd/hub &

    - name: Generate Podcast
      env:
        DISPLAY: :99.0
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        python main.py

    - name: Commit and Push
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        
        BRANCH_NAME="podcast-$(date +%Y-%m-%d)"
        
        # Find and commit new MP3 files
        if [ -n "$(find output -name '*.mp3')" ]; then
          git checkout -b $BRANCH_NAME
          git add output/
          git commit -m "Add daily podcast $(date +'%Y-%m-%d')"
          git push origin $BRANCH_NAME

          gh pr create \
            --base main \
            --head $BRANCH_NAME \
            --title "Daily Podcast Generation $(date +'%Y-%m-%d')" \
            --body "Automated daily podcast generation"
        else
          echo "No new podcast files to commit"
        fi