name: Daily Wikipedia Podcast Generation

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 1 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  generate-podcast:
    runs-on: ubuntu-latest
    environment: Daily Generator
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: PocketCoder/ephemera
        submodules: false
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsndfile1 espeak

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone Kokoro-82M
      run: |
        git clone https://github.com/PocketCoder/Kokoro-82M.git Kokoro-82M
    
    - name: Generate Podcast
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        python main.py

    - name: Authenticate GitHub CLI
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh auth status
    
    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        
        # Check if there are any new .mp3 files
        if [ -n "$(find output -name '*.mp3')" ]; then
          git checkout -b actions
          git add output/0/*.mp3
          git commit -m "Add daily podcast $(date +'%Y-%m-%d')"
          git push origin actions

          gh pr create \
            --base main \
            --head actions \
            --title "Daily Podcast Generation $(date +'%Y-%m-%d')" \
            --body "Automated daily podcast generation"
        else
          echo "No new podcast files to commit"
        fi